# Configuración para pre-commit
# https://pre-commit.com

repos:
  # Repositorio oficial de pre-commit con hooks básicos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Elimina espacios en blanco al final de las líneas
      - id: end-of-file-fixer   # Asegura que los archivos terminen con una nueva línea
      - id: check-yaml            # Revisa que los archivos YAML sean válidos
      - id: check-added-large-files # Evita que se suban archivos grandes por accidente

  # Repositorio para Black, el formateador de código
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # Repositorio para Flake8, el linter de calidad
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
