"""Add identity and regional fields to Tenant

Revision ID: 1d4891ff9ae1
Revises: ec291cd54edd
Create Date: 2026-02-07 14:10:09.687554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4891ff9ae1'
down_revision: Union[str, None] = 'ec291cd54edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
