"""Add spare_parts table and relations

Revision ID: 2a7e73792842
Revises: 65f0b5777baa
Create Date: 2026-02-01 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = '2a7e73792842'
down_revision: Union[str, None] = '65f0b5777baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('min_stock_level', sa.Integer(), nullable=False, comment='Threshold for reordering'),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_name'), 'spare_parts', ['name'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_name'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
