"""Add tenant isolation to AssetType

Revision ID: 35acf3d77b6e
Revises: 9c567dafe504
Create Date: 2026-02-06 11:49:09.615397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35acf3d77b6e'
down_revision: Union[str, None] = '9c567dafe504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_types', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_asset_types_name', table_name='asset_types')
    op.create_index(op.f('ix_asset_types_name'), 'asset_types', ['name'], unique=False)
    op.create_unique_constraint('_name_tenant_uc', 'asset_types', ['name', 'tenant_id'])
    op.create_index(op.f('ix_asset_types_tenant_id'), 'asset_types', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'asset_types', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_types', type_='foreignkey')
    op.drop_index(op.f('ix_asset_types_tenant_id'), table_name='asset_types')
    op.drop_constraint('_name_tenant_uc', 'asset_types', type_='unique')
    op.drop_index(op.f('ix_asset_types_name'), table_name='asset_types')
    op.create_index('ix_asset_types_name', 'asset_types', ['name'], unique=True)
    op.drop_column('asset_types', 'tenant_id')
    # ### end Alembic commands ###
