"""Add notifications table

Revision ID: 4f5394da9ce3
Revises: f3fb3b98d77e
Create Date: 2026-02-10 08:53:38.696945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4f5394da9ce3'
down_revision: Union[str, None] = 'f3fb3b98d77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Definición explícita del tipo ENUM
notification_level_enum = sa.Enum('TENANT', 'PLATFORM', name='notification_level')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Crear el tipo ENUM primero
    notification_level_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('notifications', sa.Column('recipient_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('level', notification_level_enum, nullable=False))
    op.add_column('notifications', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('action_url', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_reference_id', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_id'], ['id'])
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT'))
    op.add_column('notifications', sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='El UUID de la alarma o la orden de trabajo relacionada'))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_reference_id', 'notifications', ['reference_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'icon')
    op.drop_column('notifications', 'level')
    op.drop_column('notifications', 'tenant_id')
    op.drop_column('notifications', 'recipient_id')
    
    # 1. Eliminar el tipo ENUM al final
    notification_level_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
