"""update_sector_model

Revision ID: 62e77e2836e8
Revises: 92af61eab815
Create Date: 2026-02-04 12:52:03.599227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e77e2836e8'
down_revision: Union[str, None] = '92af61eab815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectors', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('sectors', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('sectors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('ix_sectors_name', table_name='sectors')
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=False)
    op.create_index(op.f('ix_sectors_tenant_id'), 'sectors', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sectors', 'sectors', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'sectors', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sectors', type_='foreignkey')
    op.drop_constraint(None, 'sectors', type_='foreignkey')
    op.drop_index(op.f('ix_sectors_tenant_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.create_index('ix_sectors_name', 'sectors', ['name'], unique=True)
    op.drop_column('sectors', 'is_active')
    op.drop_column('sectors', 'parent_id')
    op.drop_column('sectors', 'tenant_id')
    # ### end Alembic commands ###
