"""feat/monetization-feature-flags

Revision ID: 6402a3dcfb90
Revises: ca7057070aec
Create Date: 2026-02-06 01:13:07.130668

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6402a3dcfb90'
down_revision: Union[str, None] = 'ca7057070aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_parameters',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=False),
                    sa.Column('value', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_editable', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_configuration_parameters_key'), 'configuration_parameters', ['key'], unique=True)
    op.create_table('enum_types',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False,
                              comment='Ej: WorkOrderStatus, AssetStatus'),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_enum_types_name'), 'enum_types', ['name'], unique=True)
    op.create_table('asset_hierarchy',
                    sa.Column('parent_asset_type_id', sa.UUID(), nullable=False),
                    sa.Column('child_asset_type_id', sa.UUID(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_asset_type_id'], ['asset_types.id'], ),
                    sa.ForeignKeyConstraint(['parent_asset_type_id'], ['asset_types.id'], ),
                    sa.PrimaryKeyConstraint('parent_asset_type_id', 'child_asset_type_id')
                    )
    op.create_table('enum_values',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('enum_type_id', sa.UUID(), nullable=False),
                    sa.Column('value', sa.String(length=100), nullable=False, comment='El valor real, ej: IN_PROGRESS'),
                    sa.Column('label', sa.String(length=150), nullable=False,
                              comment='La etiqueta para la UI, ej: En Progreso'),
                    sa.Column('color', sa.String(length=20), nullable=True,
                              comment='Un color opcional para la UI, ej: #3b82f6'),
                    sa.ForeignKeyConstraint(['enum_type_id'], ['enum_types.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_enum_values_enum_type_id'), 'enum_values', ['enum_type_id'], unique=False)
    op.create_table('spare_parts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('part_number', sa.String(length=50), nullable=False),
                    sa.Column('stock_quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=True)
    op.create_index(op.f('ix_spare_parts_tenant_id'), 'spare_parts', ['tenant_id'], unique=False)
    op.create_table('approval_requests',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('requester_id', sa.UUID(), nullable=False),
                    sa.Column('approver_id', sa.UUID(), nullable=True),
                    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Ej: ASSET, WORK_ORDER'),
                    sa.Column('entity_id', sa.UUID(), nullable=False),
                    sa.Column('action', sa.String(length=50), nullable=False, comment='Ej: DELETE, ARCHIVE'),
                    sa.Column('payload', sa.JSON(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('request_justification', sa.String(length=500), nullable=False),
                    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_approval_requests_entity_id'), 'approval_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_type'), 'approval_requests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_table('media_items',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
                    sa.Column('context', sa.String(length=100), nullable=False),
                    sa.Column('context_id', sa.UUID(), nullable=True),
                    sa.Column('file_path', sa.String(length=1024), nullable=False),
                    sa.Column('original_filename', sa.String(length=255), nullable=False),
                    sa.Column('content_type', sa.String(length=100), nullable=False),
                    sa.Column('size_bytes', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_path')
                    )
    op.create_index(op.f('ix_media_items_context'), 'media_items', ['context'], unique=False)
    op.create_index(op.f('ix_media_items_context_id'), 'media_items', ['context_id'], unique=False)
    op.create_index(op.f('ix_media_items_tenant_id'), 'media_items', ['tenant_id'], unique=False)
    op.create_table('notifications',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('message', sa.String(length=500), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False,
                              comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT'),
                    sa.Column('reference_id', sa.String(length=255), nullable=False,
                              comment='El UUID de la alarma o la orden de trabajo relacionada'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_sectors',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('sector_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'sector_id')
                    )
    op.create_table('machine_state_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('asset_id', sa.UUID(), nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_machine_state_history_asset_id'), 'machine_state_history', ['asset_id'], unique=False)
    op.create_table('maintenance_plans',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('asset_id', sa.UUID(), nullable=False),
                    sa.Column('summary_template', sa.String(), nullable=True),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.Column('priority', sa.String(), nullable=True),
                    sa.Column('trigger_type', sa.String(), nullable=False),
                    sa.Column('interval_days', sa.Integer(), nullable=True),
                    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_maintenance_plans_asset_id'), 'maintenance_plans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_name'), 'maintenance_plans', ['name'], unique=False)
    op.create_table('maintenance_plan_tasks',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('plan_id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_maintenance_plan_tasks_plan_id'), 'maintenance_plan_tasks', ['plan_id'], unique=False)
    op.create_table('maintenance_tasks',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('work_order_id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=False,
                              comment='Description of the specific task to be performed.'),
                    sa.Column('order', sa.Integer(), nullable=True,
                              comment='The sequence order of the task within the work order.'),
                    sa.Column('is_completed', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_maintenance_tasks_work_order_id'), 'maintenance_tasks', ['work_order_id'], unique=False)
    op.create_table('work_order_provider_assignments',
                    sa.Column('work_order_id', sa.UUID(), nullable=False),
                    sa.Column('provider_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
                    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
                    sa.PrimaryKeyConstraint('work_order_id', 'provider_id')
                    )
    op.create_table('work_order_spare_parts',
                    sa.Column('work_order_id', sa.UUID(), nullable=False),
                    sa.Column('spare_part_id', sa.UUID(), nullable=False),
                    sa.Column('quantity_required', sa.Integer(), nullable=False,
                              comment='Cantidad del repuesto necesaria para la orden.'),
                    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
                    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
                    sa.PrimaryKeyConstraint('work_order_id', 'spare_part_id')
                    )
    op.create_table('work_order_user_assignments',
                    sa.Column('work_order_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
                    sa.PrimaryKeyConstraint('work_order_id', 'user_id')
                    )
    op.alter_column('alarm_rules', 'is_enabled',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.add_column('alarms', sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                                      nullable=True))
    op.add_column('alarms', sa.Column('acknowledged', sa.Boolean(), nullable=True))
    op.add_column('alarms', sa.Column('triggered_value', sa.Float(), nullable=True))
    op.alter_column('alarms', 'severity',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_constraint('alarms_acknowledged_by_id_fkey', 'alarms', type_='foreignkey')
    op.drop_column('alarms', 'triggering_value')
    op.drop_column('alarms', 'acknowledged_by_id')
    op.drop_column('alarms', 'timestamp')
    op.drop_column('alarms', 'status')
    op.add_column('asset_types', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('asset_types', sa.Column('model_number', sa.String(length=100), nullable=True))
    op.add_column('asset_types',
                  sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('asset_types',
                  sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('asset_types', 'description',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.drop_column('asset_types', 'properties_schema')
    op.add_column('assets', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('assets', sa.Column('installed_at', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('last_maintenance_at', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('warranty_expires_at', sa.Date(), nullable=True))
    op.add_column('assets',
                  sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets',
                  sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('assets', 'asset_type_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('assets', 'properties',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    comment='Propiedades específicas del activo en formato JSON.',
                    existing_nullable=True)
    op.drop_constraint('assets_tenant_id_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'description')
    op.drop_column('assets', 'is_active')
    op.drop_column('assets', 'name')
    op.drop_column('assets', 'tenant_id')
    op.alter_column('audit_logs', 'entity_type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('audit_logs', 'entity_id',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.UUID(),
                    nullable=False,
                    postgresql_using='entity_id::uuid'),
    op.alter_column('audit_logs', 'details',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    comment="JSON data detailing the change, e.g., {'from': 'old_value', 'to': 'new_value'}.",
                    existing_nullable=True)
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'tenant_id')
    op.alter_column('plans', 'limits',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.alter_column('plans', 'features',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.add_column('providers',
                  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('providers',
                  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('work_orders', 'category',
                    existing_type=sa.VARCHAR(length=50),
                    comment='CORRECTIVE, PREVENTIVE, PREDICTIVE, IMPROVEMENT',
                    existing_nullable=False)
    op.alter_column('work_orders', 'rating',
                    existing_type=sa.INTEGER(),
                    comment='Calificación de la ejecución (1-5).',
                    existing_nullable=True)
    op.alter_column('work_orders', 'feedback',
                    existing_type=sa.TEXT(),
                    comment='Comentarios cualitativos sobre la ejecución.',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'feedback',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Comentarios cualitativos sobre la ejecución.',
                    existing_nullable=True)
    op.alter_column('work_orders', 'rating',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Calificación de la ejecución (1-5).',
                    existing_nullable=True)
    op.alter_column('work_orders', 'category',
                    existing_type=sa.VARCHAR(length=50),
                    comment=None,
                    existing_comment='CORRECTIVE, PREVENTIVE, PREDICTIVE, IMPROVEMENT',
                    existing_nullable=False)
    op.drop_column('providers', 'updated_at')
    op.drop_column('providers', 'created_at')
    op.alter_column('plans', 'features',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('plans', 'limits',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.add_column('audit_logs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('audit_logs', 'details',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    comment=None,
                    existing_comment="JSON data detailing the change, e.g., {'from': 'old_value', 'to': 'new_value'}.",
                    existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
                    existing_type=sa.UUID(),
                    type_=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('audit_logs', 'entity_type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.add_column('assets', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('assets_tenant_id_fkey', 'assets', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('assets', 'properties',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    comment=None,
                    existing_comment='Propiedades específicas del activo en formato JSON.',
                    existing_nullable=True)
    op.alter_column('assets', 'asset_type_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'warranty_expires_at')
    op.drop_column('assets', 'last_maintenance_at')
    op.drop_column('assets', 'installed_at')
    op.drop_column('assets', 'location')
    op.add_column('asset_types',
                  sa.Column('properties_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                            nullable=True))
    op.alter_column('asset_types', 'description',
                    existing_type=sa.String(length=255),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.drop_column('asset_types', 'updated_at')
    op.drop_column('asset_types', 'created_at')
    op.drop_column('asset_types', 'model_number')
    op.drop_column('asset_types', 'manufacturer')
    op.add_column('alarms', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alarms', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                                      autoincrement=False, nullable=False))
    op.add_column('alarms', sa.Column('acknowledged_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('alarms',
                  sa.Column('triggering_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('alarms_acknowledged_by_id_fkey', 'alarms', 'users', ['acknowledged_by_id'], ['id'])
    op.alter_column('alarms', 'severity',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('alarms', 'triggered_value')
    op.drop_column('alarms', 'acknowledged')
    op.drop_column('alarms', 'triggered_at')
    op.alter_column('alarm_rules', 'is_enabled',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_table('work_order_user_assignments')
    op.drop_table('work_order_spare_parts')
    op.drop_table('work_order_provider_assignments')
    op.drop_index(op.f('ix_maintenance_tasks_work_order_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_plan_tasks_plan_id'), table_name='maintenance_plan_tasks')
    op.drop_table('maintenance_plan_tasks')
    op.drop_index(op.f('ix_maintenance_plans_name'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_plans_asset_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    op.drop_index(op.f('ix_machine_state_history_asset_id'), table_name='machine_state_history')
    op.drop_table('machine_state_history')
    op.drop_table('user_sectors')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_media_items_tenant_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_context_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_context'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_spare_parts_tenant_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_enum_values_enum_type_id'), table_name='enum_values')
    op.drop_table('enum_values')
    op.drop_table('asset_hierarchy')
    op.drop_index(op.f('ix_enum_types_name'), table_name='enum_types')
    op.drop_table('enum_types')
    op.drop_index(op.f('ix_configuration_parameters_key'), table_name='configuration_parameters')
    op.drop_table('configuration_parameters')
    # ### end Alembic commands ###
