"""Create alarm_rules and alarms tables

Revision ID: 65f0b5777baa
Revises: 0014
Create Date: 2026-01-30 23:18:56.077551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65f0b5777baa'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_rules_asset_id'), 'alarm_rules', ['asset_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alarm_rule_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_rule_id'], ['alarm_rules.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_alarm_rule_id'), 'alarms', ['alarm_rule_id'], unique=False)
    op.create_index(op.f('ix_alarms_asset_id'), 'alarms', ['asset_id'], unique=False)
    op.drop_index('ix_configuration_parameters_key', table_name='configuration_parameters')
    op.create_index(op.f('ix_configuration_parameters_key'), 'configuration_parameters', ['key'], unique=False)
    op.alter_column('data_sources', 'connection_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ej: {"host": "192.168.1.10", "port": 4840, "security_mode": "SignAndEncrypt"}',
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT',
               existing_nullable=False)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(length=255),
               comment='El UUID de la alarma o la orden de trabajo relacionada',
               existing_nullable=False)
    op.add_column('providers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_providers_is_active'), 'providers', ['is_active'], unique=False)
    op.drop_index('ix_sensor_readings_asset_id', table_name='sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sensor_readings_asset_id', 'sensor_readings', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_providers_is_active'), table_name='providers')
    op.drop_column('providers', 'is_active')
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='El UUID de la alarma o la orden de trabajo relacionada',
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT',
               existing_nullable=False)
    op.alter_column('data_sources', 'connection_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ej: {"host": "192.168.1.10", "port": 4840, "security_mode": "SignAndEncrypt"}',
               existing_nullable=False)
    op.drop_index(op.f('ix_configuration_parameters_key'), table_name='configuration_parameters')
    op.create_index('ix_configuration_parameters_key', 'configuration_parameters', ['key'], unique=True)
    op.drop_index(op.f('ix_alarms_asset_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alarm_rule_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_alarm_rules_asset_id'), table_name='alarm_rules')
    op.drop_table('alarm_rules')
    # ### end Alembic commands ###
