"""add_is_active_to_procurement

Revision ID: 6740f8b59b46
Revises: 29ce35333be4
Create Date: 2026-02-04 09:30:26.066234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6740f8b59b46'
down_revision: Union[str, None] = '29ce35333be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_rules_asset_id'), 'alarm_rules', ['asset_id'], unique=False)
    op.create_table('machine_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_state_history_asset_id'), 'machine_state_history', ['asset_id'], unique=False)
    op.create_table('maintenance_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('summary_template', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plans_asset_id'), 'maintenance_plans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_name'), 'maintenance_plans', ['name'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=True)
    op.create_index(op.f('ix_spare_parts_tenant_id'), 'spare_parts', ['tenant_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('triggering_value', sa.Float(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_rule_id'), 'alarms', ['rule_id'], unique=False)
    op.create_table('maintenance_plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plan_tasks_plan_id'), 'maintenance_plan_tasks', ['plan_id'], unique=False)
    op.drop_index('ix_configuration_parameters_key', table_name='configuration_parameters')
    op.create_index(op.f('ix_configuration_parameters_key'), 'configuration_parameters', ['key'], unique=False)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Nombre descriptivo, ej: 'PLC Línea de Ensamblaje 3'",
               existing_nullable=False)
    op.alter_column('data_sources', 'protocol',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Protocolo de comunicación, ej: 'OPCUA', 'MODBUS_TCP'",
               existing_nullable=False)
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Habilita o deshabilita la recolección de datos de esta fuente.')
    op.drop_index('ix_data_sources_name', table_name='data_sources')
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.drop_column('data_sources', 'updated_at')
    op.drop_column('data_sources', 'description')
    op.drop_column('data_sources', 'connection_params')
    op.drop_column('data_sources', 'created_at')
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT',
               existing_nullable=False)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(length=255),
               comment='El UUID de la alarma o la orden de trabajo relacionada',
               existing_nullable=False)
    op.add_column('providers', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('providers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('providers', 'contact_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email, phone, or address of the provider.',
               existing_nullable=True)
    op.alter_column('providers', 'specialty',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Area of expertise, e.g., Robotics, HVAC, PLC Programming.',
               existing_nullable=True)
    op.alter_column('providers', 'performance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='A score from 0-100 representing provider performance.',
               existing_nullable=True)
    op.drop_index('ix_providers_performance_score', table_name='providers')
    op.drop_index('ix_providers_specialty', table_name='providers')
    op.drop_index('ix_providers_name', table_name='providers')
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index(op.f('ix_providers_tenant_id'), 'providers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'providers', 'tenants', ['tenant_id'], ['id'])
    op.drop_index('ix_sensor_readings_asset_id', table_name='sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sensor_readings_asset_id', 'sensor_readings', ['asset_id'], unique=False)
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_index(op.f('ix_providers_tenant_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.create_index('ix_providers_name', 'providers', ['name'], unique=True)
    op.create_index('ix_providers_specialty', 'providers', ['specialty'], unique=False)
    op.create_index('ix_providers_performance_score', 'providers', ['performance_score'], unique=False)
    op.alter_column('providers', 'performance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='A score from 0-100 representing provider performance.',
               existing_nullable=True)
    op.alter_column('providers', 'specialty',
               existing_type=sa.VARCHAR(length=100),
               comment='Area of expertise, e.g., Robotics, HVAC, PLC Programming.',
               existing_nullable=True)
    op.alter_column('providers', 'contact_info',
               existing_type=sa.VARCHAR(length=255),
               comment='Email, phone, or address of the provider.',
               existing_nullable=True)
    op.drop_column('providers', 'is_active')
    op.drop_column('providers', 'tenant_id')
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='El UUID de la alarma o la orden de trabajo relacionada',
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Ej: ALARM, MAINTENANCE_ASSIGNMENT',
               existing_nullable=False)
    op.add_column('data_sources', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('data_sources', sa.Column('connection_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Ej: {"host": "192.168.1.10", "port": 4840, "security_mode": "SignAndEncrypt"}'))
    op.add_column('data_sources', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.create_index('ix_data_sources_name', 'data_sources', ['name'], unique=True)
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Habilita o deshabilita la recolección de datos de esta fuente.')
    op.alter_column('data_sources', 'protocol',
               existing_type=sa.VARCHAR(length=50),
               comment="Protocolo de comunicación, ej: 'OPCUA', 'MODBUS_TCP'",
               existing_nullable=False)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Nombre descriptivo, ej: 'PLC Línea de Ensamblaje 3'",
               existing_nullable=False)
    op.drop_index(op.f('ix_configuration_parameters_key'), table_name='configuration_parameters')
    op.create_index('ix_configuration_parameters_key', 'configuration_parameters', ['key'], unique=True)
    op.drop_index(op.f('ix_maintenance_plan_tasks_plan_id'), table_name='maintenance_plan_tasks')
    op.drop_table('maintenance_plan_tasks')
    op.drop_index(op.f('ix_alarms_rule_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_spare_parts_tenant_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_maintenance_plans_name'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_plans_asset_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    op.drop_index(op.f('ix_machine_state_history_asset_id'), table_name='machine_state_history')
    op.drop_table('machine_state_history')
    op.drop_index(op.f('ix_alarm_rules_asset_id'), table_name='alarm_rules')
    op.drop_table('alarm_rules')
    # ### end Alembic commands ###
