"""Implement dual approval for tenant deletion

Revision ID: 73bc04f74f86
Revises: dbc5277fd835
Create Date: 2026-02-08 04:49:45.536779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bc04f74f86'
down_revision: Union[str, None] = 'dbc5277fd835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
