"""update_work_order_model

Revision ID: 92af61eab815
Revises: a478813471a0
Create Date: 2026-02-04 12:05:01.701584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92af61eab815'
down_revision: Union[str, None] = 'a478813471a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('work_orders', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('work_orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.alter_column('work_orders', 'source_trigger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON data explaining the origin of the work order.',
               existing_nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='OPEN, IN_PROGRESS, ON_HOLD, COMPLETED, CANCELED',
               existing_nullable=False)
    op.alter_column('work_orders', 'priority',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='LOW, MEDIUM, HIGH, URGENT',
               existing_nullable=False)
    op.alter_column('work_orders', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='A detailed description of the issue and required work.',
               existing_nullable=True)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('work_orders', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('summary', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='A brief, one-line summary of the work to be done.'))
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.alter_column('work_orders', 'description',
               existing_type=sa.TEXT(),
               comment='A detailed description of the issue and required work.',
               existing_nullable=True)
    op.alter_column('work_orders', 'priority',
               existing_type=sa.VARCHAR(length=50),
               comment='LOW, MEDIUM, HIGH, URGENT',
               existing_nullable=False)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='OPEN, IN_PROGRESS, ON_HOLD, COMPLETED, CANCELED',
               existing_nullable=False)
    op.alter_column('work_orders', 'source_trigger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON data explaining the origin of the work order.',
               existing_nullable=True)
    op.drop_column('work_orders', 'cancellation_reason')
    op.drop_column('work_orders', 'title')
    op.drop_column('work_orders', 'tenant_id')
    # ### end Alembic commands ###
