"""update_configuration_parameter_model

Revision ID: 9c52fafffc3a
Revises: 62e77e2836e8
Create Date: 2026-02-04 14:07:34.961987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c52fafffc3a'
down_revision: Union[str, None] = '62e77e2836e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_parameters', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('configuration_parameters', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('ix_configuration_parameters_key', table_name='configuration_parameters')
    op.create_index(op.f('ix_configuration_parameters_key'), 'configuration_parameters', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_parameters_key'), table_name='configuration_parameters')
    op.create_index('ix_configuration_parameters_key', 'configuration_parameters', ['key'], unique=False)
    op.drop_column('configuration_parameters', 'is_active')
    op.drop_column('configuration_parameters', 'id')
    # ### end Alembic commands ###
