"""Add tenant_id to assets table

Revision ID: 9c567dafe504
Revises: 6402a3dcfb90
Create Date: 2026-02-06 09:07:32.427239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c567dafe504'
down_revision: Union[str, None] = '6402a3dcfb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_column('assets', 'tenant_id')
    # ### end Alembic commands ###
