"""add_tenant_and_active_to_alarming

Revision ID: a478813471a0
Revises: 6740f8b59b46
Create Date: 2026-02-04 11:49:51.368022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a478813471a0'
down_revision: Union[str, None] = '6740f8b59b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_rules', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('alarm_rules', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_alarm_rules_tenant_id'), 'alarm_rules', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'alarm_rules', 'tenants', ['tenant_id'], ['id'])
    op.add_column('alarms', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_alarms_tenant_id'), 'alarms', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'alarms', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alarms', type_='foreignkey')
    op.drop_index(op.f('ix_alarms_tenant_id'), table_name='alarms')
    op.drop_column('alarms', 'tenant_id')
    op.drop_constraint(None, 'alarm_rules', type_='foreignkey')
    op.drop_index(op.f('ix_alarm_rules_tenant_id'), table_name='alarm_rules')
    op.drop_column('alarm_rules', 'is_active')
    op.drop_column('alarm_rules', 'tenant_id')
    # ### end Alembic commands ###
