"""update_data_source_model

Revision ID: b55439afd2ad
Revises: 9c52fafffc3a
Create Date: 2026-02-04 15:13:14.245553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b55439afd2ad'
down_revision: Union[str, None] = '9c52fafffc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('data_sources', sa.Column('connection_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_data_sources_tenant_id'), 'data_sources', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'data_sources', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.drop_index(op.f('ix_data_sources_tenant_id'), table_name='data_sources')
    op.drop_column('data_sources', 'connection_params')
    op.drop_column('data_sources', 'tenant_id')
    # ### end Alembic commands ###
