"""creacion_tablas_iniciales

Revision ID: bedb54de22a4
Revises: 
Create Date: 2025-09-19 09:17:17.855483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bedb54de22a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('stock_level', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('avg_monthly_usage', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_code'), 'spare_parts', ['code'], unique=True)
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_stock_level'), 'spare_parts', ['stock_level'], unique=False)
    op.create_table('maintenance_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='maintenance_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'on_hold', 'completed', 'cancelled', name='maintenance_status_enum'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_orders_due_date'), 'maintenance_orders', ['due_date'], unique=False)
    op.create_index(op.f('ix_maintenance_orders_id'), 'maintenance_orders', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_orders_status'), 'maintenance_orders', ['status'], unique=False)
    op.drop_index('sensor_data_time_idx', table_name='sensor_data')
    op.drop_table('sensor_data')
    op.add_column('assets', sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('assets_code_key', 'assets', type_='unique')
    op.create_index(op.f('ix_assets_code'), 'assets', ['code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.drop_column('assets', 'metadata')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('assets', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_code'), table_name='assets')
    op.create_unique_constraint('assets_code_key', 'assets', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'asset_metadata')
    op.create_table('sensor_data',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quality', sa.VARCHAR(length=20), server_default=sa.text("'good'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['assets.id'], name='sensor_data_sensor_id_fkey')
    )
    op.create_index('sensor_data_time_idx', 'sensor_data', [sa.text('time DESC')], unique=False)
    op.drop_index(op.f('ix_maintenance_orders_status'), table_name='maintenance_orders')
    op.drop_index(op.f('ix_maintenance_orders_id'), table_name='maintenance_orders')
    op.drop_index(op.f('ix_maintenance_orders_due_date'), table_name='maintenance_orders')
    op.drop_table('maintenance_orders')
    op.drop_index(op.f('ix_spare_parts_stock_level'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_code'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
