"""Add soft delete and identity fields to Tenant

Revision ID: dbc5277fd835
Revises: 1d4891ff9ae1
Create Date: 2026-02-07 14:27:49.755795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc5277fd835'
down_revision: Union[str, None] = '1d4891ff9ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tenants', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'deleted_at')
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###
