"""Link work orders to spare parts

Revision ID: e5c4a3b2d1f0
Revises: 2a7e73792842
Create Date: 2026-02-01 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c4a3b2d1f0'
down_revision: Union[str, None] = '2a7e73792842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_spare_parts',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('spare_part_id', sa.UUID(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False, comment='Cantidad del repuesto necesaria para la orden.'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('work_order_id', 'spare_part_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_spare_parts')
    # ### end Alembic commands ###
