"""feat: add marketing and referral models

Revision ID: e977e9bf006c
Revises: 6c9014591a0a
Create Date: 2026-02-12 07:16:49.812878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e977e9bf006c'
down_revision: Union[str, None] = '6c9014591a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('duration', sa.Enum('ONCE', 'REPEATING', 'FOREVER', name='couponduration'), nullable=True),
    sa.Column('duration_in_months', sa.Integer(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_tenant_id', sa.UUID(), nullable=False),
    sa.Column('referred_tenant_id', sa.UUID(), nullable=True),
    sa.Column('referral_code_used', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONVERTED', 'CANCELLED', name='referralstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['referrer_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_tenant_id')
    )
    op.add_column('subscriptions', sa.Column('applied_coupon_id', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('final_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'coupons', ['applied_coupon_id'], ['id'])
    op.add_column('tenants', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tenants_referral_code'), 'tenants', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_referral_code'), table_name='tenants')
    op.drop_column('tenants', 'referral_code')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'final_price')
    op.drop_column('subscriptions', 'applied_coupon_id')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_table('marketing_campaigns')
    # ### end Alembic commands ###
