"""Add identity and regional fields to Tenant

Revision ID: ec291cd54edd
Revises: 35acf3d77b6e
Create Date: 2026-02-07 09:20:39.370747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec291cd54edd'
down_revision: Union[str, None] = '35acf3d77b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('tax_id', sa.String(length=50), nullable=True, comment='CIF, NIF, VAT ID'))
    op.add_column('tenants', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(length=100), nullable=True, comment='Email central para notificaciones del sistema'))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('tenants', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('tenants', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'config')
    op.drop_column('tenants', 'currency')
    op.drop_column('tenants', 'language')
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'billing_address')
    op.drop_column('tenants', 'tax_id')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###
