"""Add maintenance plans

Revision ID: f1d2e3c4b5a6
Revises: c1a2b3d4e5f6
Create Date: 2026-02-02 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d2e3c4b5a6'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('summary_template', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True, comment='Para TIME_BASED: ejecutar cada X días.'),
    sa.Column('last_execution_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plans_asset_id'), 'maintenance_plans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_name'), 'maintenance_plans', ['name'], unique=False)
    
    op.create_table('maintenance_plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plan_tasks_plan_id'), 'maintenance_plan_tasks', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_plan_tasks_plan_id'), table_name='maintenance_plan_tasks')
    op.drop_table('maintenance_plan_tasks')
    op.drop_index(op.f('ix_maintenance_plans_name'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_plans_asset_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    # ### end Alembic commands ###
