"""Add account manager to Tenant

Revision ID: f3fb3b98d77e
Revises: 73bc04f74f86
Create Date: 2026-02-08 05:13:12.139564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fb3b98d77e'
down_revision: Union[str, None] = '73bc04f74f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('account_manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'users', ['account_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'account_manager_id')
    # ### end Alembic commands ###
